Bug 2077835 - Return already_AddRefed instead of raw pointer from GetHiddenWindowWidget(). r=mac-reviewers,mstange,bradwerth
Make nsCocoaUtils::GetHiddenWindowWidget() return an
already_AddRefed<nsIWidget> instead of a raw nsIWidget* pointer because
the conversion from a nsCOMPtr to a raw pointer fails to compile in
C++23.

* In C++20, the returned nsCOMPtr is an lvalue. It uses nsCOMPtr's
  `operator T*() const&` conversion.

* In C++23 (P2266), the returned nsCOMPtr is a move-eligible xvalue.
  It selects the deleted `operator T*() const&& = delete` overload:

error: conversion function from 'const nsCOMPtr<T>' to 'T *' invokes a deleted function
|   operator T*() const&& = delete;

Differential Revision: https://phabricator.services.mozilla.com/D330591